### ISSUE TITLE
Reply already submitted in 2.1.2

### ISSUE THREAD

**Issue by MagicFox** [Wayaer/fl_jpush#1]
hi , 

Call this method ： deleteAlias()  caused this issue 

message log ~

```  
java.lang.IllegalStateException: Reply already submitted
02-24 18:09:39.319 28690 28690 E AndroidRuntime:        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
02-24 18:09:39.319 28690 28690 E AndroidRuntime:        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
02-24 18:09:39.319 28690 28690 E AndroidRuntime:        at fl.jpush.JPushPlugin$JPushEventReceiver.onAliasOperatorResult$lambda-2(JPushPlugin.kt:308)
02-24 18:09:39.319 28690 28690 E AndroidRuntime:        at fl.jpush.JPushPlugin$JPushEventReceiver.lambda$SEZib1541SdVl0GMh8d2wncfd7Q(Unknown Source:0)
02-24 18:09:39.319 28690 28690 E AndroidRuntime:        at fl.jpush.-$$Lambda$JPushPlugin$JPushEventReceiver$SEZib1541SdVl0GMh8d2wncfd7Q.run(Unknown Source:2)
02-24 18:09:39.319 28690 28690 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:900)
02-24 18:09:39.319 28690 28690 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:103)
02-24 18:09:39.319 28690 28690 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:219)
02-24 18:09:39.319 28690 28690 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8393)
02-24 18:09:39.319 28690 28690 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-24 18:09:39.319 28690 28690 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
02-24 18:09:39.319 28690 28690 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)


```

**Comment by Wayaer** [comment]
这个问题是你在短时间 多次调用这个方法导致的，本身方法也没有做防抖，尽量等一次调用来回完成了  再调用下一次
