### ISSUE TITLE
java.lang.AbstractMethodError: abstract method "void com.heytap.msp.push.callback.ICallBackResultService.onRegister

### ISSUE THREAD

**Issue by youyiying** [Wayaer/fl_jpush#5]
集成OPPO推送,打开App闪退,遇到过吗?
```txt
03-04 10:41:17.786  8567  8567 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void com.heytap.msp.push.callback.ICallBackResultService.onRegister(int, java.lang.String)"
03-04 10:41:17.786  8567  8567 E AndroidRuntime: 	at com.heytap.mcssdk.processor.CallBackResultProcessor.processCallBackResult(CallBackResultProcessor.java:140)
03-04 10:41:17.786  8567  8567 E AndroidRuntime: 	at com.heytap.mcssdk.processor.CallBackResultProcessor.access$000(CallBackResultProcessor.java:1)
03-04 10:41:17.786  8567  8567 E AndroidRuntime: 	at com.heytap.mcssdk.processor.CallBackResultProcessor$1.run(CallBackResultProcessor.java:9)
03-04 10:41:17.786  8567  8567 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
03-04 10:41:17.786  8567  8567 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-04 10:41:17.786  8567  8567 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:240)
03-04 10:41:17.786  8567  8567 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:351)
03-04 10:41:17.786  8567  8567 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8374)
03-04 10:41:17.786  8567  8567 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-04 10:41:17.786  8567  8567 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
03-04 10:41:17.786  8567  8567 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by youyiying** [comment]
替换com.heytap.msp_3.4.0.aar之后好了
