### ISSUE TITLE
lateinit property channel has not been initialized

### ISSUE THREAD

**Issue by youyiying** [Wayaer/fl_jpush#6]
发送离线厂商通知,打开通知闪退
`r1.p: lateinit property channel has not been initialized
                                                                                                    	at fl.jpush.JPushPlugin$a.a(JPushPlugin.kt:8)
                                                                                                    	at fl.jpush.JPushPlugin$JPushService.onCommandResult$lambda-3(JPushPlugin.kt:3)
                                                                                                    	at fl.jpush.JPushPlugin$JPushService.d(Unknown Source:0)
                                                                                                    	at s0.k.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:908)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                                    	at android.os.Looper.loop(Looper.java:219)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8679)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)`

**Comment by youyiying** [comment]
```java
        override fun onNotifyMessageOpened(activity: Context?, message: NotificationMessage?) {
            super.onNotifyMessageOpened(activity, message)
            handle.post {
                try {
                    channel.invokeMethod("onOpenNotification", message?.toMap())
                } catch (e: Exception) {
                    return@post
                }
            }
            val launch = activity!!.packageManager.getLaunchIntentForPackage(
                activity.packageName
            )
            if (launch != null) {
                launch.addCategory(Intent.CATEGORY_LAUNCHER)
                launch.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP
                activity.startActivity(launch)
            }
        }
```
暂时使用了 try-catch 块来捕获异常,避免打开离线通知异常崩溃。

**Comment by Wayaer** [comment]
提交了个新版本 试试看

**Comment by youyiying** [comment]
> 提交了个新版本 试试看

可以了,谢谢
